name: Deploy to GitHub Pages 

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to GitHub Pages 
      uses: M-Kseniia/github-pages-deploy-action@3.7.1 
      with: 
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        BRANCH: gh-pages 
        FOLDER: .
